version: '2.1'
volumes:
  darkfi:
  tor:
services:
  tor-node:
    build: ./tor
    restart: always
    depends_on:
      - ircd
    volumes:
      - tor:/var/lib/tor
    ports:
      - "9050:9050"
      - "25551:25551"
  ircd:
    build: ./ircd
    restart: 'unless-stopped'
    ports:
      - "6667:6667"
      - "6697:6697"
      - "25552:25551"
    volumes:
      - darkfi:/config
      - tor:/var/lib/tor
