version: '2.1'
volumes:
  tor:
services:
  tor-node:
    build: ./tor
    container_name: tor
    restart: unless-stopped 
    volumes:
      - tor:/var/lib/tor
    ports:
      - "25551:25551"
      - "9050:9050"
  ircd:
    build: ./ircd
    restart: unless-stopped 
    env_file:
      - ircd.env 
    container_name: ircd
    ports:
      - "6667:6667"
    volumes:
      - tor:/var/lib/tor
